apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
data:
  init.sql: |
    CREATE TABLE notes (
        id SERIAL PRIMARY KEY,
        title TEXT NOT NULL,
        content TEXT NOT NULL
    );
